"""Render and send the daily email digest via the Resend API."""
from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any

import requests

from .models import JobPosting


HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; max-width: 640px; margin: 0 auto; padding: 24px; background: #fafaf7; }}
  h1 {{ font-size: 22px; margin: 0 0 4px; letter-spacing: -0.01em; }}
  .sub {{ color: #666; font-size: 13px; margin-bottom: 28px; font-style: italic; }}
  .job {{ border-top: 1px solid #d4d4d0; padding: 18px 0; }}
  .job:last-child {{ border-bottom: 1px solid #d4d4d0; }}
  .job h2 {{ font-size: 16px; margin: 0 0 4px; font-weight: 600; }}
  .job h2 a {{ color: #1a1a1a; text-decoration: none; border-bottom: 1px solid #c79b3b; }}
  .meta {{ font-size: 12px; color: #777; margin-bottom: 6px; font-family: -apple-system, sans-serif; }}
  .meta .score {{ color: #c79b3b; font-weight: 600; }}
  .meta .source {{ background: #ece9dd; padding: 2px 6px; border-radius: 3px; margin-left: 6px; }}
  .desc {{ font-size: 13px; color: #444; line-height: 1.5; }}
  .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #d4d4d0; font-size: 12px; color: #888; font-family: -apple-system, sans-serif; }}
  .footer a {{ color: #c79b3b; }}
  .cta {{ display: inline-block; margin: 16px 0 24px; padding: 10px 18px; background: #1a1a1a; color: #fafaf7; text-decoration: none; font-family: -apple-system, sans-serif; font-size: 13px; letter-spacing: 0.02em; }}
</style>
</head>
<body>
  <h1>Daily roles &mdash; {date}</h1>
  <div class="sub">{count_new} new {plural_new}, {count_total} on the board</div>

  <a class="cta" href="{dashboard_url}">Open the full dashboard &rarr;</a>

  {jobs_html}

  <div class="footer">
    Generated by your job-aggregator. Sources: {sources}.<br>
    Edit search criteria in <code>config.yaml</code>. Adjust the digest threshold to tune volume.
  </div>
</body>
</html>"""


JOB_TEMPLATE = """<div class="job">
  <h2><a href="{url}">{title}</a></h2>
  <div class="meta">
    {company} &middot; {location} &middot; <span class="score">{score} pts</span> <span class="source">{source}</span>
  </div>
  <div class="desc">{description}</div>
</div>"""


def render_digest(new_jobs: list[JobPosting], total_count: int,
                  dashboard_url: str, sources: list[str]) -> tuple[str, str]:
    """Return (subject, html_body) for the digest email."""
    today = datetime.utcnow().strftime("%A, %B %-d")
    count_new = len(new_jobs)

    if count_new == 0:
        body = HTML_TEMPLATE.format(
            date=today,
            count_new=0,
            plural_new="matches",
            count_total=total_count,
            dashboard_url=dashboard_url,
            jobs_html='<div class="job"><div class="desc">No new matches above your threshold today. The dashboard still shows everything currently on the board.</div></div>',
            sources=", ".join(sources),
        )
        return f"Job digest — no new matches ({today})", body

    jobs_html_parts = []
    for job in new_jobs:
        desc = (job.description or "").strip()
        if len(desc) > 220:
            desc = desc[:217] + "..."
        if not desc:
            desc = "(no description)"
        jobs_html_parts.append(JOB_TEMPLATE.format(
            url=job.url,
            title=_escape(job.title),
            company=_escape(job.company or "Unknown"),
            location=_escape(job.location or "—"),
            score=job.score,
            source=_escape(job.source),
            description=_escape(desc),
        ))

    body = HTML_TEMPLATE.format(
        date=today,
        count_new=count_new,
        plural_new="match" if count_new == 1 else "matches",
        count_total=total_count,
        dashboard_url=dashboard_url,
        jobs_html="\n".join(jobs_html_parts),
        sources=", ".join(sources),
    )
    subject = f"Job digest — {count_new} new {'role' if count_new == 1 else 'roles'} ({today})"
    return subject, body


def _escape(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;"))


def send_email(subject: str, html_body: str) -> bool:
    """Send via Resend. Returns True on success."""
    api_key = os.environ.get("RESEND_API_KEY")
    email_from = os.environ.get("EMAIL_FROM")
    email_to = os.environ.get("EMAIL_TO")

    if not all([api_key, email_from, email_to]):
        print("[digest] Email env vars not set (RESEND_API_KEY/EMAIL_FROM/EMAIL_TO). Skipping send.")
        print(f"[digest] Would have sent: {subject}")
        return False

    try:
        resp = requests.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            data=json.dumps({
                "from": email_from,
                "to": [email_to],
                "subject": subject,
                "html": html_body,
            }),
            timeout=30,
        )
        if resp.status_code >= 300:
            print(f"[digest] Resend error {resp.status_code}: {resp.text}")
            return False
        print(f"[digest] Sent: {subject}")
        return True
    except requests.RequestException as e:
        print(f"[digest] Failed to send: {e}")
        return False
